name: Release

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Windows x64
          toolchain: stable-x86_64-pc-windows-msvc
          image: windows-latest
        - name: Linux x64
          toolchain: stable-x86_64-unknown-linux-gnu
          image: ubuntu-latest
    runs-on: ${{ matrix.image }}
    name: Build ${{ matrix.name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: true
    - name: Patch
      run: git apply --verbose ../patches/*.patch
      shell: bash
      working-directory: subtitler
    - name: Setup Toolchain
      run: |
        rustup toolchain install ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
    - id: version
      name: Extract Version
      run: echo "version=$(sed -nE 's/^version *= *"([0-9.]+)"$/\1/p' Cargo.toml)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Build
      run: cargo build --release --verbose
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        name: v${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}
        body: "Stable release of **Subtitle Retime**, version **${{ steps.version.outputs.version }}**"
        prerelease: false
        draft: true
        files: |
          target/release/subtitle-retime
          target/release/subtitle-retime.exe
